### ISSUE TITLE
mining issue

### ISSUE THREAD

**Issue by mileta77** [abjcoinblockchain/Abjcoin#1]
I'm follow instruction to mining and when I start miner I got "HTTP request failed: The requested URL returned error: 500 Internal Server Error"
when try to navigate thru browser I got "{"result":null,"error":{"code":-32700,"message":"Parse error"},"id":null}"
config looks OK and wallet is running

**Comment by abjcoinblockchain** [comment]
Hello this is as a result that POW is finished and you can only mine in POS.
